### ISSUE TITLE
Install Error - Yunohost on Raspberry PI

### ISSUE THREAD

**Issue by bibi99** [YunoHost-Apps/codimd_ynh#17] opened 2020-02-17 10:33 UTC
Trying to install CodiMD on yunohost / raspberry PI 3 
( Debian 9.11 - yunohost stable version": "3.6.5.3")

- created dedicated subdomain 
- use https://github.com/YunoHost-Apps/codimd_ynh as a source url for the app installation

Got a warning : 
"WARNING - yarn: error: no such option: --pure-lockfile"

Extract of log file :

2020-02-17 10:21:19,965: DEBUG - + replace_string=**********
2020-02-17 10:21:19,966: DEBUG - + sudo sed --in-place s@__DB_PASS__@**********@g ../conf/.sequelizerc.example
2020-02-17 10:21:20,067: DEBUG - + cp ../conf/.sequelizerc.example /var/www/codimd/.sequelizerc
2020-02-17 10:21:20,068: DEBUG - + ynh_script_progression '--message=Building application... (this may take some time and resources!)'
2020-02-17 10:21:20,069: DEBUG - + set +x
2020-02-17 10:21:20,070: DEBUG - + set +x
2020-02-17 10:21:20,071: DEBUG - + echo '! Helper used in legacy mode !'
2020-02-17 10:21:20,072: DEBUG - + set +x
2020-02-17 10:21:20,073: DEBUG - + echo '[#######++...........] > Building application... (this may take some time and resources!)'
2020-02-17 10:21:20,074: DEBUG - + set -x
2020-02-17 10:21:20,075: DEBUG - + pushd /var/www/codimd
2020-02-17 10:21:20,075: DEBUG - /var/www/codimd /var/cache/yunohost/from_file/codimd_ynh-master/scripts
2020-02-17 10:21:20,076: DEBUG - + ./bin/setup
2020-02-17 10:21:20,077: DEBUG - copy config files
2020-02-17 10:21:20,078: DEBUG - install packages
2020-02-17 10:21:21,283: DEBUG - + ynh_exit_properly
2020-02-17 10:21:21,284: WARNING - Usage: yarn [options]
2020-02-17 10:21:21,286: INFO - [#######++...........] > Building application... (this may take some time and resources!)
2020-02-17 10:21:21,288: DEBUG - + local exit_code=2
2020-02-17 10:21:21,288: WARNING - 
2020-02-17 10:21:21,290: DEBUG - + '[' 2 -eq 0 ']'
2020-02-17 10:21:21,291: WARNING - yarn: error: no such option: --pure-lockfile
2020-02-17 10:21:21,292: DEBUG - + trap '' EXIT
2020-02-17 10:21:21,293: DEBUG - + set +eu
2020-02-17 10:21:21,293: DEBUG - + sleep 0.5
2020-02-17 10:21:21,796: DEBUG - + ynh_print_err '--message=!!\n  codimd'\''s script has encountered an error. Its execution was cancelled.\n!!'
2020-02-17 10:21:21,797: DEBUG - + local legacy_args=m
2020-02-17 10:21:21,798: DEBUG - + args_array=([m]=message=)
2020-02-17 10:21:21,800: DEBUG - + declare -Ar args_array
2020-02-17 10:21:21,801: DEBUG - + local message
2020-02-17 10:21:21,802: DEBUG - + ynh_handle_getopts_args '--message=!!\n  codimd'\''s script has encountered an error. Its execution was cancelled.\n!!'
2020-02-17 10:21:21,804: DEBUG - + set +x
2020-02-17 10:21:21,905: DEBUG - + ynh_print_log '\e[91m\e[1m[ERR]\e[0m !!\n  codimd'\''s script has encountered an error. Its execution was cancelled.\n!!'
2020-02-17 10:21:21,907: WARNING - [91m[1m[ERR][0m !!
2020-02-17 10:21:21,912: DEBUG - + echo -e '\e[91m\e[1m[ERR]\e[0m !!\n  codimd'\''s script has encountered an error. Its execution was cancelled.\n!!'
2020-02-17 10:21:21,913: WARNING -   codimd's script has encountered an error. Its execution was cancelled.

**Comment by Lab-8916100448256** [comment] 2020-03-09 15:29
Same error here trying to install on a Debian 9 virtual machine with yunohost 3.6.5.3. 

The code that is calling yarn with the option: --pure-lockfile is in [CodiMD setup script](https://github.com/codimd/server/blob/master/bin/setup). So I guess there isn't much that can be done on yunohost install script side.

This was working fine a few month ago when I installed it on another server.
I noticed that latest yarn version is 1.22.1 but on the other server the version of yarn that is installed is 1.19.2

I tried pinning yarn version to 1.19.2 before installing CodiMD to work-around the issue which seems to have worked.

To pin the version of yarn I have added the file /etc/apt/preferences.d/yarn with this content :
```
Package: yarn
Pin: version 1.19.*
Pin-Priority: 999
```

**Comment by alexAubin** [comment] 2020-04-27 02:12
Duplicate of other issue, closing because that should be fixed by https://github.com/YunoHost-Apps/codimd_ynh/pull/19 (the --pure-lockfile thing)

Feel free to reopen if needed

(Though beware about install RPi, the initial build takes a huge amount of resources... Ideally would be nice to have pre-built assets but idk if the upstream provides this)

**Closed as completed by alexAubin** 2020-04-27 02:12 UTC
Labels: bug, help wanted
